import "../styles/global.css";
import { Metadata } from "next";
import Navigation from "@/components/module/navigation";

export const metadata: Metadata = {
  title: {
    template: "%s | nextmovie",
    default: "nextmovie",
  },
  description: "Generated by Next.js",
};
//title은 브라우저 탭에 나타나는 이름

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        {/* <Navigation /> */}
        {children}
      </body>
    </html>
  );
}

//lauout 컴포넌트에 있는 export 된 디폴트 컴포넌트를 렌더링 한다.
//children은 렌더링할 컴포넌트를 받는다.
//컴포넌트중 다수는 페이직 간에 재사용 되는 경우가 많음
//예를 들면 nav바나 푸터같은 경우가 그러하다.

// export default function Layout({ children }) {
//   return (
//   <>
//   < Navbar / >
//   < main >{children}< /main >
//   < Footer / >
//   </>
//   )
//   }
//이런식으로 사용 가능

//모든 routes에 공유되는 컴포넌트는 밖에 놔둠
